pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.shared.theme
import qs.app.services
import qs.app
import qs.shared.i18n
import "../../shared/utils/ThemePalette.js" as ThemePalette
import "../../shared/utils/TemplateExpr.js" as TemplateExpr

Singleton {
    id: root

    property var templates: []
    readonly property var builtinTemplates: templates.filter(t => t.origin === "builtin")
    readonly property var userTemplates: templates.filter(t => t.origin === "user")
    property bool ready: false
    property string error: ""
    property string operationError: ""
    readonly property bool busy: mutation.running || pendingOperation !== null
    readonly property bool adding: busy && (pendingOperation ? pendingOperation.name : operation) === "add"
    property var pendingOperation: null
    property bool refreshPending: false
    property string operation: ""
    property string operationId: ""
    readonly property string script: Paths.scriptPath("theme", "manage-matugen-templates.sh")

    signal validated(bool valid)
    signal added(string templateId)
    signal removed(string templateId)

    // Per-scheme preview palettes for the dashboard theme picker, generated by
    // generate-matugen-previews.sh (one matugen run per variant against the
    // current source). Lives here, not in the page: UI files carry no file
    // I/O. Falls back to the legacy clavis/ directory until the generator has
    // written the nyxuri/ path.
    property var schemePreviews: ({})
    property bool previewsLegacyFallback: false

    FileView {
        id: previewsFile

        path: Paths.generatedHome + (root.previewsLegacyFallback ? "/clavis/scheme-previews.json" :
                                                                   "/nyxuri/scheme-previews.json")
        watchChanges: true
        printErrors: false
        onLoaded: {
            try {
                root.schemePreviews = JSON.parse(previewsFile.text());
            } catch (e) {
                root.schemePreviews = ({});
            }
        }
        onLoadFailed: {
            if (!root.previewsLegacyFallback) {
                root.previewsLegacyFallback = true;
                // Path rebinding alone does not start a load; force one.
                Qt.callLater(previewsFile.reload);
                return;
            }
            root.schemePreviews = ({});
        }
    }

    // Template engine state (P4): the dual-mode palette written by the
    // generation script feeds the Noctalia palette mirror and every template
    // render. Falls back to the legacy clavis/ directory like the other
    // generated files.
    property bool modesLegacyFallback: false
    property var tokenColors: ({})
    property string activeMode: PersonalizationConfig.themeMode === "light" ? "light" : "dark"
    property string mirrorError: ""
    property var renderErrors: ({})
    property string mirrorPath: Paths.xdgConfigHome + "/noctalia/palettes/nyxuri.json"

    FileView {
        id: modesFile

        path: Paths.generatedHome + (root.modesLegacyFallback ? "/clavis/palette-modes.json" :
                                                                "/nyxuri/palette-modes.json")
        watchChanges: true
        printErrors: false
        onLoaded: {
            try {
                root.applyPaletteModes(JSON.parse(modesFile.text()));
            } catch (e) {
                console.warn("Unable to apply palette modes:", e);
                root.tokenColors = {};
            }
        }
        onFileChanged: modesFile.reload()
        onLoadFailed: error => {
            if (error === FileViewError.FileNotFound && !root.modesLegacyFallback) {
                root.modesLegacyFallback = true;
                // Path rebinding alone does not start a load; force one.
                Qt.callLater(modesFile.reload);
                return;
            }
            root.tokenColors = {};
        }
    }

    FileView {
        id: mirrorFile

        path: root.mirrorPath
        watchChanges: false
        atomicWrites: true
        printErrors: false
        onSaved: root.mirrorError = ""
        onSaveFailed: error => root.mirrorError = FileViewError.toString(error)
    }

    function applyPaletteModes(data) {
        if (!data || typeof data !== "object" || Array.isArray(data)) {
            throw new Error("Expected a palette-modes object");
        }
        const modes = {
            "dark": data.dark,
            "light": data.light
        };
        const colors = {};
        for (const mode in modes) {
            const palette = modes[mode];
            if (!palette || typeof palette !== "object" || Array.isArray(palette)) {
                throw new Error("Missing " + mode + " palette");
            }
            const withTerminals = ThemePalette.paletteWithTerminals(palette, mode);
            for (const token in withTerminals) {
                if (!colors[token]) {
                    colors[token] = {};
                }
                colors[token][mode] = withTerminals[token];
            }
        }
        root.tokenColors = colors;
        root.writeMirror(modes.dark || {}, modes.light || {});
        root.renderAll();
    }

    // Managed artifact: the Noctalia custom palette directory only receives
    // this one generated file; user-created palettes next to it are never
    // touched. Atomic write keeps the previous copy readable on failure.
    function writeMirror(darkPalette, lightPalette) {
        const body = ThemePalette.noctaliaPaletteJson(darkPalette, lightPalette);
        mirrorFile.setText(JSON.stringify(body, null, 2) + "\n");
    }

    function templateById(templateId) {
        return root.templates.find(t => t.id === templateId) || null;
    }
    function containsId(templateId) {
        return root.templateById(templateId) !== null;
    }
    function refresh() {
        if (listing.running || mutation.running) {
            root.refreshPending = true;
            return;
        }
        root.refreshPending = false;
        listing.running = true;
    }
    function runOperation(name, args) {
        if (root.busy)
            return false;
        root.operationError = "";
        if (listing.running) {
            root.pendingOperation = {
                name: name,
                args: args
            };
            return true;
        }
        root.operation = name;
        root.operationId = args[0];
        mutation.command = ["bash", root.script, name, ...args];
        mutation.running = true;
        return true;
    }
    function validate(templateId, source, output, hook) {
        return root.runOperation("validate", [templateId, source, output, hook]);
    }
    function add(templateId, source, output, hook) {
        return root.runOperation("add", [templateId, source, output, hook]);
    }
    function remove(templateId) {
        return root.runOperation("remove", [templateId]);
    }
    function openLocation(template) {
        const path = template && typeof template.inputPath === "string" ? template.inputPath : "";
        if (!path.startsWith("/") || path.endsWith("/") || /[\u0000-\u001f\u007f]/.test(path) || path.endsWith(
                    "/.") || path.endsWith("/..")) {
            console.warn("Cannot open template location: invalid absolute source path");
            return;
        }
        FileActionService.run("reveal", path);
    }

    // ---- render queue ----------------------------------------------------
    // One template at a time: load its source, render through the expression
    // subset, atomically write the output, run its hook. Failures are recorded
    // per template and never block the remaining queue.

    function enabledTemplateIds() {
        const ids = [];
        for (const template of root.templates) {
            if (template.valid && PersonalizationConfig.isMatugenTemplateEnabled(template.id) && ids.indexOf(
                        template.id) === -1)
                ids.push(template.id);
        }
        return ids;
    }

    function renderAll() {
        if (!root.ready || Object.keys(root.tokenColors).length === 0) {
            return;
        }
        root.activeMode = PersonalizationConfig.themeMode === "light" ? "light" : "dark";
        root.renderQueue = root.enabledTemplateIds();
        root.renderNext();
    }

    function renderTemplate(id) {
        if (Object.keys(root.tokenColors).length === 0) {
            return;
        }
        root.activeMode = PersonalizationConfig.themeMode === "light" ? "light" : "dark";
        if (root.renderQueue.indexOf(id) === -1) {
            root.renderQueue.push(id);
        }
        root.renderNext();
    }

    property var renderQueue: []
    property string renderingId: ""
    property string renderingOutput: ""
    property string renderingHook: ""
    // The current hook's Process, created per hook from hookProcessComponent.
    property var hookProcess: null
    // Diagnostic surface for the render queue: hookRunning distinguishes a
    // wedged hook (stuck true) from a spawn request that never landed.
    readonly property bool hookRunning: root.hookProcess !== null
    // The output FileView rebinds per template; its path-change load (or the
    // FileNotFound miss on first render) must settle before setText, or the
    // async load can race the write. Both asset views report readiness and
    // writeOutput fires once input text AND output path are settled.
    property bool outputReady: false
    property string pendingRendered: ""
    // The output view's content, captured when its settle event fires and
    // updated to the rendered text when a write completes. The identical-
    // render check reads this instead of calling FileView.text(): a text()
    // call in the settle window starts a second async read on the view, and
    // the following save disowns it — Quickshell 0.3.1 then drops the save
    // completion and the queue wedges.
    property string outputContent: ""

    function renderNext() {
        if (root.renderingId !== "" || root.renderQueue.length === 0) {
            return;
        }
        const id = root.renderQueue.shift();
        const template = root.templateById(id);
        if (!template || !template.valid || !PersonalizationConfig.isMatugenTemplateEnabled(id)) {
            root.renderNext();
            return;
        }
        if (!template.outputPath) {
            // A render with no destination would stall the queue silently;
            // surface it like any other per-template failure instead.
            root.renderingId = id;
            root.renderFailed("Template has no output path");
            return;
        }
        root.renderingId = id;
        root.renderingOutput = template.outputPath;
        root.renderingHook = template.postHook || "";
        root.pendingRendered = "";
        root.watchStep("Template read");
        // Rebinding to the same path (repeat render of one template) starts no
        // new load, so the settle wait only applies to a real rebind.
        if (templateOutput.path === template.outputPath) {
            root.outputReady = true;
        } else {
            root.outputReady = false;
            templateOutput.path = template.outputPath;
        }
        templateInput.path = template.inputPath;
        Qt.callLater(templateInput.reload);
    }

    FileView {
        id: templateInput

        path: ""
        watchChanges: false
        printErrors: false
        onLoaded: root.renderLoaded(templateInput.text())
        onLoadFailed: error => root.renderFailed("Unable to read template: " + FileViewError.toString(error))
    }

    function renderLoaded(text) {
        if (root.renderingId === "") {
            // Late completion of a step the watchdog already failed.
            return;
        }
        let rendered;
        try {
            rendered = TemplateExpr.render(root.renderingId, text, root.tokenColors, root.activeMode);
        } catch (e) {
            root.renderFailed(String(e));
            return;
        }
        if (rendered === "") {
            // An empty render would silently stall writeOutput's non-empty
            // gate; fail the template like any other render error instead.
            root.renderFailed("Template rendered an empty result");
            return;
        }
        root.pendingRendered = rendered;
        root.writeOutput();
    }

    FileView {
        id: templateOutput

        path: ""
        watchChanges: false
        atomicWrites: true
        // Synchronous saves: Quickshell 0.3.1 loses FileView operation
        // completions under rapid interleaved reads and writes on one view
        // (observed: async writers whose saved() never arrives), which would
        // wedge the queue. An inline save has no async completion to lose.
        blockWrites: true
        printErrors: false
        onLoaded: root.outputSettled()
        onLoadFailed: root.outputSettled()
        onSaved: root.renderSaved()
        onSaveFailed: error => root.renderFailed("Unable to write output: " + FileViewError.toString(error))
    }

    function outputSettled() {
        if (root.renderingId === "" || root.outputReady) {
            return;
        }
        // The settle handler runs right after the view's updateState, so this
        // text() is served from the loaded state and starts no new read.
        root.outputContent = templateOutput.text();
        root.outputReady = true;
        root.writeOutput();
    }

    function writeOutput() {
        if (!root.outputReady || root.pendingRendered === "" || root.renderingId === "") {
            return;
        }
        if (!root.renderingOutput) {
            root.renderFailed("Template has no output path");
            return;
        }
        if (root.outputContent === root.pendingRendered) {
            // Quickshell FileView.setText no-ops when the text equals the
            // loaded file content: nothing is written and onSaved never
            // fires. An unchanged render is still a completed render —
            // finish it here, or the queue stalls on this template forever
            // and every later renderAll silently no-ops. Hooks still run;
            // they are idempotent and kitty-apply reloads live instances.
            root.renderSaved();
            return;
        }
        templateOutput.setText(root.pendingRendered);
    }

    function renderSaved() {
        const id = root.renderingId;
        const nextErrors = JSON.parse(JSON.stringify(root.renderErrors));
        delete nextErrors[id];
        root.renderErrors = nextErrors;
        root.outputContent = root.pendingRendered;
        const hook = root.renderingHook;
        if (hook === "") {
            root.renderDone();
            return;
        }
        // Hooks come from the registry (builtin or user-managed); they run as
        // one argument to bash -c with the template directory injected, never
        // concatenated with other shell words. XDG_* values are the raw user
        // homes — Paths.cacheHome already carries the nyxuri suffix and the
        // vendored hooks append their own. A fresh Process per hook: a reused
        // instance was observed to silently drop a spawn request, and a lost
        // exit would freeze the queue exactly like the setText no-op. The
        // watchdog keeps that class of failure bounded either way.
        const inputDir = templateInput.path.substring(0, templateInput.path.lastIndexOf("/"));
        const process = hookProcessComponent.createObject(root);
        root.hookProcess = process;
        process.command = ["bash", "-c", hook];
        process.environment = {
            "TEMPLATE_DIR": inputDir,
            "HOME": Paths.homeDir,
            "XDG_CONFIG_HOME": Paths.xdgConfigHome,
            "XDG_CACHE_HOME": Quickshell.env("XDG_CACHE_HOME") || Paths.homeDir + "/.cache"
        };
        root.watchStep("Hook");
        process.running = true;
    }

    function finishHook(failed, message) {
        stepWatchdog.stop();
        const process = root.hookProcess;
        if (process) {
            process.finished = true;
            process.running = false;
            process.destroy();
            root.hookProcess = null;
        }
        if (failed)
            root.renderFailed(message);
        else
            root.renderDone();
    }

    Component {
        id: hookProcessComponent

        Process {
            property bool finished: false

            onExited: exitCode => {
                if (this.finished)
                    return;
                root.finishHook(exitCode !== 0, "Hook failed with exit code " + exitCode);
            }
        }
    }

    // Bounds every async wait in the queue (template read, output settle,
    // hook run): a lost FileView or Process event degrades to a recorded
    // per-template failure instead of a permanently stuck renderingId, which
    // would silently swallow every later renderAll.
    property string watchStepLabel: ""
    Timer {
        id: stepWatchdog

        interval: 10000
        onTriggered: root.renderFailed(root.watchStepLabel + " timed out after 10 seconds")
    }

    function watchStep(step) {
        root.watchStepLabel = step;
        stepWatchdog.restart();
    }

    function renderFailed(message) {
        const id = root.renderingId;
        const nextErrors = JSON.parse(JSON.stringify(root.renderErrors));
        nextErrors[id] = message;
        root.renderErrors = nextErrors;
        console.warn("Template render failed:", id, message);
        root.renderDone();
    }

    function renderDone() {
        stepWatchdog.stop();
        root.renderingId = "";
        root.renderingOutput = "";
        root.renderingHook = "";
        root.renderNext();
    }

    Connections {
        target: PersonalizationConfig
        function onSettingsLoaded() {
            if (root.ready)
                PersonalizationConfig.discoverMatugenTemplates(root.templates);
        }
        function onThemeModeChanged() {
            root.activeMode = PersonalizationConfig.themeMode === "light" ? "light" : "dark";
        }
    }

    Component.onCompleted: root.refresh()

    FileView {
        path: Paths.userMatugenDir + "/config.toml"
        watchChanges: true
        printErrors: false
        onFileChanged: refreshDebounce.restart()
    }
    Timer {
        id: refreshDebounce
        interval: 150
        onTriggered: root.refresh()
    }
    Process {
        id: listing
        command: ["bash", root.script, "list"]
        stdout: StdioCollector {
            id: listOutput
        }
        stderr: StdioCollector {
            id: listError
        }
        onExited: exitCode => {
            try {
                if (exitCode !== 0)
                    throw new Error(listError.text.trim() || I18n.tr("Unable to read template"));
                const result = JSON.parse(listOutput.text);
                if (result.schemaVersion !== 1 || !Array.isArray(result.templates))
                    throw new Error(I18n.tr("Invalid template data"));
                if (JSON.stringify(result.templates) !== JSON.stringify(root.templates))
                    root.templates = result.templates;
                root.error = result.errors.join("\n");
                root.ready = true;
                PersonalizationConfig.discoverMatugenTemplates(root.templates);
                // The palette-modes FileView usually loads before this listing
                // process exits; its renderAll was gated on ready and skipped.
                // Drive one pass now so a boot-time regeneration still renders.
                root.renderAll();
            } catch (e) {
                root.error = String(e);
            }
            if (root.pendingOperation) {
                const pending = root.pendingOperation;
                root.pendingOperation = null;
                root.runOperation(pending.name, pending.args);
            } else if (root.refreshPending) {
                Qt.callLater(root.refresh);
            }
        }
    }
    Process {
        id: mutation
        stdout: StdioCollector {
            id: mutationOutput
        }
        stderr: StdioCollector {
            id: mutationError
        }
        onExited: exitCode => {
            let ok = false;
            try {
                const result = JSON.parse(mutationOutput.text);
                if (result.schemaVersion !== 1)
                    throw new Error(I18n.tr("Invalid template data"));
                ok = exitCode === 0 && result.ok === true;
                root.operationError = ok ? "" : result.error || I18n.tr("Template operation failed");
            } catch (e) {
                root.operationError = mutationError.text.trim() || String(e);
            }
            if (root.operation === "validate") {
                root.validated(ok);
            } else if (ok && root.operation === "add") {
                // Existing saved choices are respected, including a restored ID.
                root.added(root.operationId);
            } else if (ok && root.operation === "remove") {
                root.templates = root.templates.filter(t => t.origin !== "user" || t.id !== root.operationId);
                if (!root.containsId(root.operationId))
                    PersonalizationConfig.removeMatugenTemplate(root.operationId);
                root.removed(root.operationId);
            }
            root.refresh();
        }
    }

    Component.onDestruction: {
        refreshDebounce.stop();
        if (listing)
            listing.running = false;
        if (mutation)
            mutation.running = false;
        if (root.hookProcess) {
            root.hookProcess.running = false;
            root.hookProcess.destroy();
            root.hookProcess = null;
        }
        hookWatchdog.stop();
    }
}
